//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESTOR_SERVICIO.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gestor_dbEntities : DbContext
    {
        public gestor_dbEntities()
            : base("name=gestor_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<carrito> carritos { get; set; }
        public virtual DbSet<categoria> categorias { get; set; }
        public virtual DbSet<cliente> clientes { get; set; }
        public virtual DbSet<estado> estados { get; set; }
        public virtual DbSet<informe> informes { get; set; }
        public virtual DbSet<permiso> permisos { get; set; }
        public virtual DbSet<precio> precios { get; set; }
        public virtual DbSet<producto> productos { get; set; }
        public virtual DbSet<productos_carritos> productos_carritos { get; set; }
        public virtual DbSet<productos_ventas> productos_ventas { get; set; }
        public virtual DbSet<proveedore> proveedores { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
        public virtual DbSet<venta> ventas { get; set; }
    }
}
