//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESTOR_SERVICIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.Productos_Carritos = new HashSet<Productos_Carritos>();
            this.Productos_Ventas = new HashSet<Productos_Ventas>();
        }
    
        public int id_producto { get; set; }
        public string nombre_producto { get; set; }
        public string caracteristicas_producto { get; set; }
        public Nullable<long> stock { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> id_precio { get; set; }
        public Nullable<int> id_categoria { get; set; }
        public Nullable<int> id_proveedor { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Precio Precio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Productos_Carritos> Productos_Carritos { get; set; }
        public virtual Proveedore Proveedore { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Productos_Ventas> Productos_Ventas { get; set; }
    }
}
