//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESTOR_SERVICIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos_carritos
    {
        public int id_productos_carritos { get; set; }
        public Nullable<int> id_carrito { get; set; }
        public Nullable<int> id_producto { get; set; }
        public Nullable<int> cantidad_producto_carrito { get; set; }
    
        public virtual carrito carrito { get; set; }
        public virtual producto producto { get; set; }
    }
}
